platform :ios, '6.0'
pod 'AFNetworking'
pod 'SWRevealViewController', '~> 1.0.4'
pod 'SDWebImage', '~> 3.4'
pod 'SVProgressHUD'
pod 'RATreeView'
pod 'MagicalRecord', '~> 2.2'
pod 'MWPhotoBrowser'
pod 'TUSafariActivity'
pod 'LDProgressView', '~> 1.1'

link_with 'BuildHawk'